# <<: !include lora_garage_door_subs.yml


substitutions:
  device_name: erv-return-box
  device_name_opener: garage-door-opener
  device_name_receiver: t3-lora32
  eth_cs: GPIO9
  eth_clk: GPIO10
  eth_miso: GPIO11
  eth_mosi: GPIO12
  eth_int: GPIO13
  eth_rst: GPIO14

  scl_pin: GPIO5
  sda_pin: GPIO4


#define LORA_RST            12
#define LORA_DI0            32
#define RADIO_DIO_1         33
#define RADIO_DIO_2         34
#define LORA_SS             5
#define LORA_MISO           19
#define LORA_MOSI           23
#define LORA_SCK            18

  lora_clk_pin: GPIO17
  lora_mosi_pin: GPIO15
  lora_miso_pin: GPIO16
  lora_dio0_pin: GPIO7
  lora_cs_pin: GPIO18
  lora_rst_pin: GPIO6

external_components:
  - source:
      type: local
      path: ../../../my_components # path relative to Devices folder
    components: [packet_transport]



#include ""
#include ""
# esphome:
#   name: $device_name
  # includes:
    # - <erv_ctrl\pressurePeakFilter.h>
    # - <freertos/FreeRTOS.h>
    # - <freertos/task.h>
  # on_boot:
  #   - priority: -100
  #     then:
  #       - lock.lock: man_door_lock
  # platformio_options:
  #   board_build.flash_mode: dio

esphome:
  name: $device_name
  # on_boot:
  #   - priority: -100
  #     then:
  #       - sensor.template.publish:
  #           id: garage_door_state_request
  #           state: -1
  #       - sensor.template.publish:
  #           id: local_garage_door_state
  #           state: 0

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  flash_size: 8MB
  framework:
    type: esp-idf


preferences:
  # the default of 1min is far too short--flash chip is rated for approx 100k writes.
  flash_write_interval: "240h"

api:
  # password: ""
ota:
  platform: esphome
  password: ""

logger:
  # level: very_verbose
  level: INFO
  # logs:
  #   sensor: WARN
  #   button: INFO
  #   wifi: INFO
  #   adc: INFO
  #   adc.common: INFO
  #   adc.esp32: INFO
  #   ntc: INFO
  #   mdns: INFO
  #   climate: INFO
  #   resistance: INFO
  #   ledc.output: INFO
  #   homeassistant.text_sensor: INFO
  #   pid.sensor: INFO



ethernet:
  type: W5500
  clk_pin: $eth_clk
  mosi_pin: $eth_mosi
  miso_pin: $eth_miso
  cs_pin: $eth_cs
  interrupt_pin: $eth_int
  reset_pin: $eth_rst

time:
  - platform: homeassistant

text_sensor:
  - platform: version
    name: "$device_name Version"

# SPI bus for LoRa radio
spi:
  # interface: spi3
  # id: spi3
  # clk_pin: GPIO17
  # mosi_pin: GPIO15
  # miso_pin: GPIO16
  interface: spi3
  id: spi3
  clk_pin: $lora_clk_pin
  mosi_pin: $lora_mosi_pin
  miso_pin: $lora_miso_pin

# LoRa Radio Configuration (SX1276/SX1278)
sx127x:
  # data_rate: 100khz
  spi_id: spi3
  setup_priority: 801
  dio0_pin: $lora_dio0_pin
  cs_pin: $lora_cs_pin
  rst_pin: $lora_rst_pin
  pa_pin: BOOST
  pa_power: 10
  bandwidth: 125_0kHz
  crc_enable: true
  frequency: 915MHz
  # frequency: 433920000
  modulation: LORA
  rx_start: true
  sync_value: 0x12
  preamble_size: 8
  spreading_factor: 7
  coding_rate: CR_4_6
  on_packet:
    then:
      - lambda: |-
          id(receivedPackets)++;

globals:
  - { id: receivedPackets, type: int, initial_value: "0"}
  - { id: sentPackets, type: int, initial_value: "0"}

# Example button to send LoRa packet
button:
  - platform: restart
    name: "$device_name Restart"
  - platform: template
    name: "Send LoRa Packet"
    on_press:
      then:
        - lambda: id(sentPackets)++;
        - sx127x.send_packet:
            data: [0xDE, 0xAD, 0xBE, 0xEF, 0xCA, 0xFE, 0xBA, 0xBE]


packet_transport:
  platform: sx127x
  update_interval: never
  encryption: "780905cb-619f-4663-b246-256ba69c2ea6"
  rolling_code_enable: true
  ping_pong_enable: true
  retry_sending_sensor_states_enable: true
  retry_timeout: 10s
  sensors:
    - id: garage_door_state_request
      broadcast_id: garage_door_state_request_2
  providers:
    - name: $device_name_opener
      encryption: "780905cb-619f-4663-b246-256ba69c2ea6"

switch:
  - platform: template
    name: "remote Switch"
    optimistic: true
    id: local_switch
    turn_on_action:
      - sensor.template.publish: { id: garage_door_state_request, state: 12}
    turn_off_action:
      - sensor.template.publish: { id: garage_door_state_request, state: 8}


binary_sensor:
  - platform: packet_transport
    provider: $device_name_opener
    type: status
    name: opener connection status
    internal: false

sensor:
  - { platform: uptime, id: uptime_seconds, update_interval: 1min }
  - { platform: template, id: uptime_days, name: "$device_name uptime", update_interval: 1min, 
      device_class: duration, entity_category: "diagnostic", unit_of_measurement: "d", accuracy_decimals: 2,
      lambda: !lambda "return id(uptime_seconds).state / 86'400;"}
  - platform: packet_transport
    provider: $device_name_opener
    id: opener_garage_door_state
    name: remote state
    internal: false
    on_value:
      - { lambda: !lambda 'ESP_LOGI("lora", "remote got state: %.2f from opener", x);' }
  - platform: template
    id: garage_door_state_request
    name: local state
    internal: false
    update_interval: never

