substitutions:
  device_name: garage-temp-sensor
  friendly_device_name: garage-temp-sensor
  eth_cs: GPIO9
  eth_clk: GPIO10
  eth_miso: GPIO11
  eth_mosi: GPIO12
  eth_int: GPIO13
  eth_rst: GPIO14

  scl: GPIO4
  sda: GPIO5
  sda2: GPIO6
  scl2: GPIO7
  one_wire: GPIO15
  DS18B20_06: "0xa13c01d607cdea28"



external_components:
  - source:
      type: local
      path: ..\..\my_components # path relative to Devices folder

esphome:
  name: $device_name
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  flash_size: 8MB
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESPTOOLPY_FLASHSIZE_8MB: y

preferences:
  # the default of 1min is far too short--flash chip is rated for approx 100k writes.
  flash_write_interval: "48h"

api:
  # password: ""
ota:
  platform: esphome
  password: ""

logger:
  level: verbose
  logs:
    wifi: warn
    sensor: debug
    adc.esp32: INFO
    adc.common: INFO
    logger: INFO
    cd74hc4067: INFO
    mdns: INFO
    ledc.output: INFO

ethernet:
  type: W5500
  clk_pin: $eth_clk
  mosi_pin: $eth_mosi
  miso_pin: $eth_miso
  cs_pin: $eth_cs
  interrupt_pin: $eth_int
  reset_pin: $eth_rst

time:
  - platform: homeassistant

button:
  - platform: restart
    name: "$device_name Restart"

text_sensor:
  - platform: version
    name: "$device_name Version"

i2c:
  - id: bus_a
    sda: $sda
    scl: $scl
    scan: true
  - id: bus_b
    sda: $sda2
    scl: $scl2
    scan: true

one_wire:
  - platform: gpio
    pin: $one_wire
    id: one_wire_bus_a


.defaultfilters:
  - &moving_avg
    sliding_window_moving_average:
      window_size: 30
      send_every: 30

sensor:
  - { platform: uptime, id: uptime_seconds, update_interval: 1min }
  - { platform: template, id: uptime_days, name: "$device_name uptime", update_interval: 1min, 
      device_class: duration, entity_category: "diagnostic", unit_of_measurement: "d", accuracy_decimals: 2,
      lambda: !lambda "return id(uptime_seconds).state / 86'400;"}
  - platform: sht4x
    update_interval: 1s
    i2c_id: bus_a
    temperature:
      name: "ERV Intake Temperature"
      id: erv_in_temp
      unit_of_measurement: "°C"
      filters: [ *moving_avg ]
    humidity:
      name: "ERV Intake Humidity"
      id: erv_in_humid
      filters: [ *moving_avg ]
  - platform: sht4x
    update_interval: 1s
    i2c_id: bus_b
    temperature:
      name: "Garage Attic Temperature"
      id: garage_attic_temp
      unit_of_measurement: "°C"
      filters: [ *moving_avg ]
    humidity:
      name: "Garage Attic Humidity"
      id: garage_attic_humid
      filters: [ *moving_avg ]
  # - platform: dallas_temp
  #   address: $DS18B20_06
  #   id: "rt_ds18_6"
  #   name: "Roof Temp"
  # resolution: 12
  # one_wire_id: one_wire_bus_a
  # update_interval: 1s
  # filters: [ *moving_avg, delta: 0.1 ]
