substitutions:
  device_name: hvac-monitor
  DS18B20_07: "0xa20119280563f828"
  DS18B20_08: "0x62011926f4fb3c28"

esphome:
  name: $device_name
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  flash_size: 8MB
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESPTOOLPY_FLASHSIZE_8MB: y

preferences:
  # the default of 1min is far too short--flash chip is rated for approx 100k writes.
  flash_write_interval: "120h"

api:
  # password: ""
ota:
  platform: esphome
  password: ""

logger:
  level: info


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "$device_name AP"
    password: "BiSG9yrKP394"
captive_portal:

time:
  - platform: homeassistant

button:
  - platform: restart
    name: "$device_name Restart"

text_sensor:
  - platform: version
    name: "$device_name Version"


one_wire:
  - platform: gpio
    pin: GPIO11
    id: one_wire_bus_a

.defaultfilters:
  - &moving_avg
    sliding_window_moving_average:
      window_size: 60
      send_every: 30

sensor:
  - { platform: uptime, id: uptime_seconds, update_interval: 1min }
  - { platform: template, id: uptime_days, name: "$device_name uptime", update_interval: 1min, 
      device_class: duration, entity_category: "diagnostic", unit_of_measurement: "d", accuracy_decimals: 2,
      lambda: !lambda "return id(uptime_seconds).state / 86'400;"}
  - platform: dallas_temp
    address: $DS18B20_07
    id: "hvac_sup_ds18_7"
    name: "HV-AC Supply Air Temp"
    # resolution: 12
    one_wire_id: one_wire_bus_a
    update_interval: 1s
    filters: [ *moving_avg, delta: 0.1 ]
  - platform: dallas_temp
    address: $DS18B20_08
    name: "HV-AC Return Air Temp"
    id: "hvac_ret_ds18_8"
    # resolution: 12
    one_wire_id: one_wire_bus_a
    update_interval: 1s
    filters: [ *moving_avg, delta: 0.1 ]





