substitutions:
  device_name: central-return-damper
  # device_name: dc-circuit-breaker
  eth_cs: GPIO9
  eth_clk: GPIO10
  eth_miso: GPIO11
  eth_mosi: GPIO12
  eth_int: GPIO13
  eth_rst: GPIO14

  motor_speed_pin: GPIO6
  motor_dir_A: GPIO4
  motor_dir_B: GPIO5
  stop_1: GPIO7
  stop_2: GPIO17

  one_wire_a: GPIO15
  one_wire_b: GPIO16

  servo_pot_pin: GPIO18
  servo_pin: GPIO8

  DS18B20_02: "0x0a3c01d6077f2128" 
  DS18B20_03: "0xfd3c01d60725b328" 
  DS18B20_04: "0x5b3c01d607cabd28"
  DS18B20_05: "0x343c01d6076b0428"

#  19, 20, 3

external_components: 
  - source:
      type: local
      path: ../../my_components # path relative to Devices folder

esphome:
  name: $device_name
  platformio_options:
    board_build.flash_mode: dio
  on_boot:
    - priority: -100
      then:
        - lambda: |-
            // if cover is at one of the end stops move to the opposite end
            if(id(close_endstop_binary_sensor).state){
              id(frd_cover).make_call().set_command_open().perform();
              id(open_start_time) = millis();
            }
            else if(id(open_endstop_binary_sensor).state){
              id(frd_cover).make_call().set_command_close().perform();
              id(close_start_time) = millis();
            }
            else {
              id(startup_setup) = true;
              id(frd_cover).make_call().set_command_close().perform();
            }

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  flash_size: 8MB
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESPTOOLPY_FLASHSIZE_8MB: y

preferences:
  # the default of 1min is far too short--flash chip is rated for approx 100k writes.
  flash_write_interval: "240h"

api:
  # password: ""
ota:
  platform: esphome
  password: ""

logger:
  level: info

ethernet:
  type: W5500
  clk_pin: $eth_clk
  mosi_pin: $eth_mosi
  miso_pin: $eth_miso
  cs_pin: $eth_cs
  interrupt_pin: $eth_int
  reset_pin: $eth_rst

time:
  - platform: homeassistant

button:
  - platform: restart
    name: "$device_name Restart"

text_sensor:
  - platform: version
    name: "$device_name Version"

output:
  - platform: ledc
    pin: $motor_speed_pin
    id: motor_speed
    # frequency: 19531Hz
    frequency: 120Hz
  - platform: gpio
    pin: $motor_dir_A
    id: motor_dir_1
  - platform: gpio
    pin: $motor_dir_B
    id: motor_dir_2
  - {platform: ledc, id: servo_output, pin: $servo_pin, frequency: 200 Hz}

globals:
  - { id: running_startup, type: bool, initial_value: "true" }
  - { id: startup_setup, type: bool, initial_value: "false" }
  - { id: open_start_time, type: uint32_t, initial_value: "0" }
  - { id: close_start_time, type: uint32_t, initial_value: "0" }
  - { id: speed, type: uint32_t, initial_value: "50" }

binary_sensor:
  - platform: gpio
    name: "Open Endstop"
    id: open_endstop_binary_sensor
    pin: { number: $stop_2, mode: { input: true, pulldown : true } }
    filters: [ delayed_on_off: 100ms]
    on_state: 
      then:
        - lambda: |-
            ESP_LOGI("cover", "Open endstop triggered");
            if (id(running_startup)) {
              auto now = millis();
              ESP_LOGI("cover", "Open endstop triggered at %lu ms, started at %lu: dif %lu", now, id(open_start_time), now - id(open_start_time));
              // id(running_startup) = false;
            }
  - platform: gpio
    name: "Close Endstop"
    id: close_endstop_binary_sensor
    pin: { number: $stop_1, mode: { input: true, pulldown : true } }
    filters: [ delayed_on_off: 100ms]
    on_state: 
      then:
        - lambda: |-
            ESP_LOGI("cover", "Close endstop triggered");
            if (id(running_startup)) {
              auto now = millis();
              if (id(startup_setup)) {
                id(startup_setup) = false;
              }
              // id(running_startup) = false;
              ESP_LOGI("cover", "close endstop triggered at %lu ms, started at %lu: dif %lu", now, id(close_start_time), now - id(close_start_time));

            }

cover:
  - platform: endstop
    id: frd_cover
    name: "floor return damper"
    open_action:
      - output.turn_off: motor_dir_2
      - output.turn_on: motor_dir_1
      # - output.turn_on: motor_speed
      - output.set_level: { id: motor_speed, level: !lambda "return id(speed);" }
    open_duration: 9s
    open_endstop: open_endstop_binary_sensor
    close_action:
      - output.turn_off: motor_dir_1
      - output.turn_on: motor_dir_2
      # - output.turn_on: motor_speed
      - output.set_level: { id: motor_speed, level:  !lambda "return id(speed);" }
    close_duration: 9s
    close_endstop: close_endstop_binary_sensor
    stop_action:
      - output.turn_off: motor_speed
      - output.turn_off: motor_dir_1
      - output.turn_off: motor_dir_2
  # - platform: template
  #   device_class: damper
  #   id: test_vent
  #   name: printer vent_erv
  #   restore_mode: NO_RESTORE
  #   has_position: true
  #   open_action: { servo.write: { id: servo_, level: !lambda "return id(damper).open_position;" } }
  #   close_action: { servo.write: { id: servo_, level: !lambda "return  id(damper).close_position;" }}
  #   position_action: { servo.write: { id: servo_, level: !lambda "return id(damper).tilt_to_servo_position(pos);" }}
  #   lambda: "return id(damper).get_tilt();"
  #   tilt_action: { servo.write: { id: servo_, level: !lambda "return id(damper).tilt_to_servo_position(tilt);" }}
  #   tilt_lambda: !lambda "return id(damper).get_tilt();"


.defaultfilters:
  - &moving_avg
    sliding_window_moving_average:
      window_size: 60
      send_every: 30

one_wire:
  - platform: gpio
    pin: $one_wire_a
    id: one_wire_bus_a
  - platform: gpio
    pin: $one_wire_b
    id: one_wire_bus_b


sensor:
  - { platform: uptime, id: uptime_seconds, update_interval: 1min }
  - { platform: template, id: uptime_days, name: "$device_name uptime", update_interval: 1min, 
      device_class: duration, entity_category: "diagnostic", unit_of_measurement: "d", accuracy_decimals: 2,
      lambda: !lambda "return id(uptime_seconds).state / 86'400;"}
  - { platform: dallas_temp, address: $DS18B20_05, name: "Slab Edge Temp", id: "slab_one",  one_wire_id: one_wire_bus_b, update_interval: 1s, filters: [ *moving_avg, delta: 0.05 ]}
  - { platform: dallas_temp, address: $DS18B20_04, name: "Ground Edge Temp", id: "ground_one",  one_wire_id: one_wire_bus_b, update_interval: 1s, filters: [ *moving_avg, delta: 0.05 ]}
  - { platform: dallas_temp, address: $DS18B20_02, name: "Slab Center Temp", id: "slab_two",  one_wire_id: one_wire_bus_a, update_interval: 1s, filters: [ *moving_avg, delta: 0.05 ]}
  - { platform: dallas_temp, address: $DS18B20_03, name: "Ground Center Temp", id: "ground_two",  one_wire_id: one_wire_bus_a, update_interval: 1s, filters: [ *moving_avg, delta: 0.05 ]}
    # resolution: 12
    
  - { platform: adc, id: servo_potentiometer, name: "A v_meas", pin: $servo_pot_pin, update_interval: 250ms, attenuation: 12db }

# hard_stop_damper:
#   - {id: damper, servo_position_sensor: servo_potentiometer, servo: servo_, 
#     open_at_center: true, switch_open_and_close: false, check_position_physically: true }

servo:
  - { id: servo_, output: servo_output, transition_length: 0s, auto_detach_time: 1000ms, max_level: 50%, min_level: 1%} # transition_length: 7s





number:
  - platform: template
    name: vent Control
    min_value: 0
    initial_value: 50
    max_value: 100
    step: 1
    optimistic: true
    set_action:
      then:
        - globals.set: { id: speed, value: x }
        # - servo.write:
        #     id: servo_
        #     level: !lambda "return id(speed).tilt_to_servo_position(( x / 100.0));"