substitutions:
  device_name: xiao-thermostat
  thermostat_name: "Xiao Thermostat"
  sda_pin: GPIO21
  scl_pin: GPIO22
  encode_pin_1: GPIO23
  encode_pin_2: GPIO16
  # encode_sw_pin: GPIO14
  relay_pin: GPIO17
  # relay_pin2: GPIO19
  disp_rst_pin: GPIO18
  disp_busy_pin: GPIO19

# LED: 15
# RF: 14   High: external, Low: built in
# STRAPPING:  8:F, 9:PU, 15:F
# D    -> GPIO
# 0    -> 0
# 1    -> 1
# 2    -> 2
# 3    -> 21
# 4    -> 22
# 5    -> 23
# 6    -> 16
# 7    -> 17
# 8    -> 19
# 9    -> 20
# 10   -> 18
# UNDER BOARD: 4, 5, 6, 7


<<: !include BaseDevices/ThermostatBase.yml
