substitutions:
  device_name: jacob-thermostat
  thermostat_name: "Jacob Thermostat"
  sda_pin: GPIO21
  scl_pin: GPIO22
  encode_pin_1: GPIO35
  encode_pin_2: GPIO34
  # encode_sw_pin: GPIO14
  relay_pin: GPIO26
  disp_rst_pin: GPIO25
  disp_busy_pin: GPIO19
  # strapping 2, 8, 9  
<<: !include BaseDevices/ThermostatBase.yml


#   sda_pin: GPIO21
#   scl_pin: GPIO22
#   encode_pin_1: GPIO34
#   encode_pin_2: GPIO35
#   # encode_sw_pin: GPIO14
#   relay_pin: GPIO26
#   relay_pin2: GPIO25
#   disp_rst_pin: GPIO19
# # unused 23, 18, 17, 16, 13 4, 2