substitutions:
  device_name: sub-grade-temp-sensor
  one_wire_a: GPIO4
  one_wire_b: GPIO5

esphome:
  name: $device_name
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  flash_size: 8MB
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESPTOOLPY_FLASHSIZE_8MB: y

preferences:
  # the default of 1min is far too short--flash chip is rated
  # for approx 100k writes.
  flash_write_interval: "48h"

api:
  # password: ""
ota:
  platform: esphome
  password: ""

logger:
  level: INFO


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "$device_name AP"
    password: "BiSG9yrKP394"
captive_portal:

time:
  - platform: homeassistant

button:
  - platform: restart
    name: "$device_name Restart"

text_sensor:
  - platform: version
    name: "$device_name Version"


one_wire:
  - platform: gpio
    pin: $one_wire_a
    id: one_wire_bus_a
  - platform: gpio
    pin: $one_wire_b
    id: one_wire_bus_b

sensor:
  - platform: dallas_temp
    # address: 0x1234567812345628
    name: "near wall temp 12 in"
    resolution: 10
    one_wire_id: one_wire_bus_a
    update_interval: 300s
  - platform: dallas_temp
    # address: 0x1234567812345628
    name: "near wall temp 1 in"
    resolution: 10
    one_wire_id: one_wire_bus_b
    update_interval: 300s







