substitutions:
  device_name: erv-return-box
  device_name_opener: garage-door-opener
  eth_cs: GPIO9
  eth_clk: GPIO10
  eth_miso: GPIO11
  eth_mosi: GPIO12
  eth_int: GPIO13
  eth_rst: GPIO14

  servo_pot_pin: GPIO2
  servo_pin: GPIO41

  uart_tx_pin: GPIO38
  uart_rx_pin: GPIO39

  scl_pin: GPIO5
  sda_pin: GPIO4

  step_pin: GPIO19
  dir_pin: GPIO20
  en_pin: GPIO6

external_components:
  - source:
      type: local
      path: ../my_components # path relative to Devices folder



#include ""
#include ""
esphome:
  name: $device_name
  includes:
    # - <erv_ctrl\pressurePeakFilter.h>
    - <freertos/FreeRTOS.h>
    - <freertos/task.h>
  # on_boot:
  #   - priority: -100
  #     then:
  #       - lock.lock: man_door_lock
  # platformio_options:
  #   board_build.flash_mode: dio

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  flash_size: 8MB
  framework:
    type: esp-idf
    # sdkconfig_options:
    #   CONFIG_FREERTOS_USE_TRACE_FACILITY: y
    #   CONFIG_FREERTOS_GENERATE_RUN_TIME_STATS: y
    #   CONFIG_FREERTOS_USE_STATS_FORMATTING_FUNCTIONS: y
      # CONFIG_ESPTOOLPY_FLASHSIZE_8MB: y


#define configUSE_TRACE_FACILITY        1
#define configUSE_STATS_FORMATTING_FUNCTIONS 1


preferences:
  # the default of 1min is far too short--flash chip is rated for approx 100k writes.
  flash_write_interval: "240h"

api:
  # password: ""
ota:
  platform: esphome
  password: ""

logger:
  # level: very_verbose
  level: info

ethernet:
  type: W5500
  clk_pin: $eth_clk
  mosi_pin: $eth_mosi
  miso_pin: $eth_miso
  cs_pin: $eth_cs
  interrupt_pin: $eth_int
  reset_pin: $eth_rst

time:
  - platform: homeassistant

# SPI bus for LoRa radio
# spi:
#   interface: spi3
#   id: spi3
#   clk_pin: GPIO15
#   mosi_pin: GPIO7
#   miso_pin: GPIO6

# i2c:
#   - id: bus_a
#     sda: $sda_pin
#     scl: $scl_pin
#     scan: true

button:
  - platform: restart
    name: "$device_name Restart"
  # - platform: template
  #   id: run_call
  #   name: "home vent servo"
  #   on_press:
  #     then:
  #       lambda: !lambda |-
  #         id(damper)->setup();
  # - platform: template
  #   id: center_servo
  #   name: "center servo"
  #   on_press:
  #     then:
  #       - servo.write:
  #           id: servo_
  #           level: !lambda "return 0.5;"

text_sensor:
  - platform: version
    name: "$device_name Version"

# LoRa Radio Configuration (SX1276/SX1278)
# sx127x:
#   data_rate: 1000khz
#   spi_id: spi3
#   setup_priority: 801
#   dio0_pin: GPIO17
#   cs_pin:
#     number: GPIO16
#     inverted: false
#   rst_pin: GPIO18
#   pa_pin: BOOST
#   pa_power: 10
#   bandwidth: 125_0kHz
#   crc_enable: true
#   frequency: 915MHz
#   # frequency: 433920000
#   modulation: LORA
#   rx_start: true
#   sync_value: 0x12
#   preamble_size: 8
#   spreading_factor: 7
#   coding_rate: CR_4_6
#   on_packet:
#     then:
#       - lambda: |-
#           id(receivedPackets)++;
#           ESP_LOGI("lora", "Received packet RSSI: %.2f dBm, SNR: %.2f dB", rssi, snr);

# globals:
#   - { id: receivedPackets, type: int, initial_value: "0"}
#   - { id: sentPackets, type: int, initial_value: "0"}

# packet_transport:
#   platform: sx127x
#   update_interval: 30s
#   encryption: "780905cb-619f-4663-b246-256ba69c2ea6"
#   rolling_code_enable: true
#   ping_pong_enable: true
#   binary_sensors:
#     - relay3_sensor
#   providers:
#     - name: $device_name_opener
#       encryption: "780905cb-619f-4663-b246-256ba69c2ea6"

switch:
  - platform: gpio
    pin: GPIO1
    id: relay3
    name: "receiver switch"

# binary_sensor:
#   - platform: template
#     id: relay3_sensor
#     lambda: "return id(relay3).state;"
#     internal: false

#   - platform: packet_transport
#     provider: $device_name_opener
#     id: relay1_sensor
#     on_press:
#       switch.turn_on: relay3
#     on_release:
#       switch.turn_off: relay3
#     name: opener state extra
#     internal: false
#   - platform: packet_transport
#     provider: $device_name_opener
#     type: status
#     name: opener connection status extra
#     internal: false

sensor:
  - { platform: uptime, id: uptime_seconds, update_interval: 1min }
  - { platform: template, id: uptime_days, name: "$device_name uptime", update_interval: 1min, 
      device_class: duration, entity_category: "diagnostic", unit_of_measurement: "d", accuracy_decimals: 2,
      lambda: !lambda "return id(uptime_seconds).state / 86'400;"}
  # - { platform: adc, id: servo_potentiometer, name: "v_meas", pin: $servo_pot_pin, update_interval: 250ms, attenuation: 12db }
  # - platform: mhz19
  #   update_interval: 2s
  #   co2:
  #     name: MH-Z19 CO2 Value
  #   temperature:
  #     name: MH-Z19 Temperature
  # - platform: mics_4514
  #   nitrogen_dioxide:
  #     name: Nitrogen Dioxide
  #   carbon_monoxide:
  #     name: Carbon Monoxide
  #   hydrogen:
  #     name: Hydrogen
  #   ethanol:
  #     name: Ethanol
  #   methane:
  #     name: Methane
  #   ammonia:
  #     name: Ammonia
  #   update_interval: 2s




# hard_stop_damper:
#   - {id: damper, servo_position_sensor: servo_potentiometer, servo: servo_, 
#     open_at_center: true, switch_open_and_close: false, open_offset: 0 }


# servo:
#   - { id: servo_, output: servo_output, transition_length: 7s, auto_detach_time: 1000ms, max_level: 50%, min_level: 1%}

# output:
#   - {platform: ledc, id: servo_output, pin: $servo_pin, frequency: 200 Hz}


# number:
  # - platform: template
  #   name: vent Control
  #   min_value: 0
  #   initial_value: 100
  #   max_value: 100
  #   step: 1
  #   optimistic: true
  #   set_action:
  #     then:
  #       - servo.write:
  #           id: servo_
  #           level: !lambda "return id(damper).tilt_to_servo_position(( x / 100.0));"
#   - platform: template
#     name: servo Control
#     min_value: -8
#     initial_value: 50
#     max_value: 100
#     step: 1
#     optimistic: true
#     set_action:
#       then:
#         - servo.write:
#             id: servo_
#             level: !lambda "return x / 100.0;"


# uart:
#   tx_pin: $uart_tx_pin
#   rx_pin: $uart_rx_pin
#   baud_rate: 9600


  # xTaskCreatePinnedToCore(&ESP32Camera::framebuffer_task,
  #                         "framebuffer_task",           // name
  #                         FRAMEBUFFER_TASK_STACK_SIZE,  // stack size
  #                         this,                         // task pv params
  #                         1,                            // priority
  #                         nullptr,                      // handle
  #                         1                             // core

cover:
  - platform: template
    device_class: damper
    id: attic_return_vent
    name: attic return vent
    restore_mode: NO_RESTORE
    has_position: true
    open_action: 
        - stepper.set_target: { id: right_door_servo, target: !lambda "return 4000 * 8;" }
        # - lambda: |-
        #     char buffer[1024]; 
            
        #     ESP_LOGI("TASKS", "--- Current RTOS Tasks ---");
        #     ESP_LOGI("TASKS", "Task Name\tState\tPrio\tStack\tNum\tCore");
            
        #     // Populate the buffer with task statistics
        #     vTaskList(buffer);
            
        #     // Print the result
        #     ESP_LOGI("TASKS", "%s", buffer);
        #     ESP_LOGI("TASKS", "---------------------------\n");

    close_action: { stepper.set_target: { id: right_door_servo, target: !lambda "return  0;" }}
    tilt_action: { stepper.set_target: { id: right_door_servo, target: !lambda "return 4000 * 4;" }}
    tilt_lambda: !lambda "return id(right_door_servo).current_position;"
    lambda: "return id(right_door_servo).current_position < 200 ? esphome::cover::COVER_CLOSED : esphome::cover::COVER_OPEN;"


# 400steps per rotation
stepper:
  - platform: a4988
    id: right_door_servo
    step_pin: $step_pin
    dir_pin: $dir_pin
    sleep_pin: $en_pin
    # max_speed: 16000 steps/s # 2400 RPM
    # acceleration: 8000
    # deceleration: 8000
    max_speed: 4000 steps/s # 2400 RPM
    acceleration: 2000
    deceleration: 2000




