substitutions:
  device_name: erv-return-box
  eth_cs: GPIO9
  eth_clk: GPIO10
  eth_miso: GPIO11
  eth_mosi: GPIO12
  eth_int: GPIO13
  eth_rst: GPIO14

  servo_pot_pin: GPIO2
  servo_pin: GPIO41

  uart_tx_pin: GPIO38
  uart_rx_pin: GPIO39

  scl_pin: GPIO5
  sda_pin: GPIO4

  step_pin: GPIO20
  dir_pin: GPIO21
  en_pin: GPIO8

  device_name_opener: garage-door-opener
  device_name_receiver: t3-lora32

external_components:
  - source:
      type: local
      path: ../my_components # path relative to Devices folder



#include ""
#include ""
esphome:
  name: $device_name
  # includes:
    # - <erv_ctrl\pressurePeakFilter.h>
    # - <freertos/FreeRTOS.h>
    # - <freertos/task.h>
  # on_boot:
  #   - priority: -100
  #     then:
  #       - lock.lock: man_door_lock
  # platformio_options:
  #   board_build.flash_mode: dio

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  flash_size: 8MB
  framework:
    type: esp-idf
    # sdkconfig_options:
    #   CONFIG_FREERTOS_USE_TRACE_FACILITY: y
    #   CONFIG_FREERTOS_GENERATE_RUN_TIME_STATS: y
    #   CONFIG_FREERTOS_USE_STATS_FORMATTING_FUNCTIONS: y
      # CONFIG_ESPTOOLPY_FLASHSIZE_8MB: y


#define configUSE_TRACE_FACILITY        1
#define configUSE_STATS_FORMATTING_FUNCTIONS 1


preferences:
  # the default of 1min is far too short--flash chip is rated for approx 100k writes.
  flash_write_interval: "240h"

api:
  # password: ""
ota:
  platform: esphome
  password: ""

logger:
  # level: very_verbose
  level: INFO
  # logs:
  #   sensor: WARN
  #   button: INFO
  #   wifi: INFO
  #   adc: INFO
  #   adc.common: INFO
  #   adc.esp32: INFO
  #   ntc: INFO
  #   mdns: INFO
  #   climate: INFO
  #   resistance: INFO
  #   ledc.output: INFO
  #   homeassistant.text_sensor: INFO
  #   pid.sensor: INFO



ethernet:
  type: W5500
  clk_pin: $eth_clk
  mosi_pin: $eth_mosi
  miso_pin: $eth_miso
  cs_pin: $eth_cs
  interrupt_pin: $eth_int
  reset_pin: $eth_rst

time:
  - platform: homeassistant

# SPI bus for LoRa radio
spi:
  interface: spi3
  id: spi3
  clk_pin: GPIO17
  mosi_pin: GPIO15
  miso_pin: GPIO16

# i2c:
#   - id: bus_a
#     sda: $sda_pin
#     scl: $scl_pin
#     scan: true

button:
  - platform: restart
    name: "$device_name Restart"
  # - platform: template
  #   id: run_call
  #   name: "home vent servo"
  #   on_press:
  #     then:
  #       lambda: !lambda |-
  #         id(damper)->setup();
  # - platform: template
  #   id: center_servo
  #   name: "center servo"
  #   on_press:
  #     then:
  #       - servo.write:
  #           id: servo_
  #           level: !lambda "return 0.5;"
  # - platform: ld2450
  #   ld2450_id: ld2450_radar
  #   factory_reset:
  #     name: "LD2450 Factory Reset"
  #     entity_category: "config"
  #   restart:
  #     name: "LD2450 Restart"
  #     entity_category: "config"


text_sensor:
  - platform: version
    name: "$device_name Version"
  # - platform: ld2450
  #   ld2450_id: ld2450_radar
  #   version:
  #     name: "LD2450 Firmware"
  #   mac_address:
  #     name: "LD2450 BT MAC"
    # target_1:
    #   direction:
    #     name: "Target-1 Direction"
    # target_2:
    #   direction:
    #     name: "Target-2 Direction"
    # target_3:
    #   direction:
    #     name: "Target-3 Direction"


uart:
  id: uart_ld2450
  tx_pin: GPIO19
  rx_pin: 
    number: GPIO20
    mode:
      input: true
      pullup: true
  baud_rate: 256000
  parity: NONE
  stop_bits: 1

ld2450:
  id: ld2450_radar
  uart_id: uart_ld2450

# select:
#   - platform: ld2450
#     ld2450_id: ld2450_radar
#     baud_rate:
#       name: "Baud rate"
#     zone_type:
#       name: "Zone Type"

# switch:
#   - platform: ld2450
#     ld2450_id: ld2450_radar
#     bluetooth:
#       name: "Bluetooth"
#     multi_target:
#       name: "Multi Target Tracking"


# number:
#   - platform: ld2450
#     ld2450_id: ld2450_radar
#     presence_timeout:
#       name: "Timeout"
#     zone_1:
#       x1:
#         name: Zone-1 X1
#       y1:
#         name: Zone-1 Y1
#       x2:
#         name: Zone-1 X2
#       y2:
#         name: Zone-1 Y2

.defaultfilters:
  - &moving_avg  [ throttle: 0.25s, sliding_window_moving_average: { window_size: 20, send_every: 10 } ]
  - &slow  [ delta: 0.9, throttle: 5s ]


sensor:
  - { platform: uptime, id: uptime_seconds, update_interval: 1min }
  - { platform: template, id: uptime_days, name: "$device_name uptime", update_interval: 1min, 
      device_class: duration, entity_category: "diagnostic", unit_of_measurement: "d", accuracy_decimals: 2,
      lambda: !lambda "return id(uptime_seconds).state / 86'400;"}
  - platform: ld2450
    ld2450_id: ld2450_radar
    target_count: { name: Presence Target Count, filters: *slow }
    still_target_count: { name: Still Target Count, filters: *slow }
    moving_target_count: { name: Moving Target Count, filters: *slow }
    target_1:
      x: { name: Target-1 X, filters: *moving_avg }
      y: { name: Target-1 Y, filters: *moving_avg  }
      speed: { name: Target-1 Speed, filters: *moving_avg  }
      angle: { name: Target-1 Angle, filters: *moving_avg  }
      distance: { name: Target-1 Distance, filters: *moving_avg  }
      resolution: { name: Target-1 Resolution, filters: [ throttle: 5s ] }
    target_2:
      x: { name: Target-2 X, filters: *moving_avg  }
      y: { name: Target-2 Y, filters: *moving_avg  }
      speed: { name: Target-2 Speed, filters: *moving_avg  }
      angle: { name: Target-2 Angle, filters: *moving_avg  }
      distance: { name: Target-2 Distance, filters: *moving_avg  }
      resolution: { name: Target-2 Resolution, filters: [ throttle: 5s ] }
    zone_1:
      target_count: { name: Zone-1 All Target Count, filters: *slow }
      still_target_count: { name: Zone-1 Still Target Count, filters: *slow }
      moving_target_count: { name: Zone-1 Moving Target Count, filters: *slow }
        
  # - { platform: adc, id: servo_potentiometer, name: "v_meas", pin: $servo_pot_pin, update_interval: 250ms, attenuation: 12db }
  # - platform: mhz19
  #   update_interval: 2s
  #   co2:
  #     name: MH-Z19 CO2 Value
  #   temperature:
  #     name: MH-Z19 Temperature
  # - platform: mics_4514
  #   nitrogen_dioxide:
  #     name: Nitrogen Dioxide
  #   carbon_monoxide:
  #     name: Carbon Monoxide
  #   hydrogen:
  #     name: Hydrogen
  #   ethanol:
  #     name: Ethanol
  #   methane:
  #     name: Methane
  #   ammonia:
  #     name: Ammonia
  #   update_interval: 2s




# hard_stop_damper:
#   - {id: damper, servo_position_sensor: servo_potentiometer, servo: servo_, 
#     open_at_center: true, switch_open_and_close: false, open_offset: 0 }


# servo:
#   - { id: servo_, output: servo_output, transition_length: 7s, auto_detach_time: 1000ms, max_level: 50%, min_level: 1%}

# output:
#   - {platform: ledc, id: servo_output, pin: $servo_pin, frequency: 200 Hz}


# number:
  # - platform: template
  #   name: vent Control
  #   min_value: 0
  #   initial_value: 100
  #   max_value: 100
  #   step: 1
  #   optimistic: true
  #   set_action:
  #     then:
  #       - servo.write:
  #           id: servo_
  #           level: !lambda "return id(damper).tilt_to_servo_position(( x / 100.0));"
#   - platform: template
#     name: servo Control
#     min_value: -8
#     initial_value: 50
#     max_value: 100
#     step: 1
#     optimistic: true
#     set_action:
#       then:
#         - servo.write:
#             id: servo_
#             level: !lambda "return x / 100.0;"


# uart:
#   tx_pin: $uart_tx_pin
#   rx_pin: $uart_rx_pin
#   baud_rate: 9600


  # xTaskCreatePinnedToCore(&ESP32Camera::framebuffer_task,
  #                         "framebuffer_task",           // name
  #                         FRAMEBUFFER_TASK_STACK_SIZE,  // stack size
  #                         this,                         // task pv params
  #                         1,                            // priority
  #                         nullptr,                      // handle
  #                         1                             // core

# servo_garage_door:
#   id: garage_door_controller
#   motors:
#       # dir_pin: $dir_pin
#       # step_pin: $step_pin
#       # enable_pin: $en_pin
#       # alarm_pin: GPIO41
#       # in_place_pin: GPIO2
#       steps_per_rotation: 400
#   cs_pin:
#     number: GPIO18
#     inverted: false

# cover:
#   - platform: template
#     device_class: damper
#     id: attic_return_vent
#     name: attic return vent
#     restore_mode: NO_RESTORE
#     has_position: true
#     open_action: 
#         # - stepper.set_target: { id: right_door_servo, target: !lambda "return 4000 * 8;" }
#         - lambda: |-
#             id(garage_door_controller).move_servo(16000 * 1 * 10, true, 16000, 4000, 0);
#         # - lambda: |-
#         #     char buffer[1024]; 
            
#         #     ESP_LOGI("TASKS", "--- Current RTOS Tasks ---");
#         #     ESP_LOGI("TASKS", "Task Name\tState\tPrio\tStack\tNum\tCore");
            
#         #     // Populate the buffer with task statistics
#         #     vTaskList(buffer);
            
#         #     // Print the result
#         #     ESP_LOGI("TASKS", "%s", buffer);
#         #     ESP_LOGI("TASKS", "---------------------------\n");

#     # close_action: { stepper.set_target: { id: right_door_servo, target: !lambda "return  0;" }}
#     # tilt_action: { stepper.set_target: { id: right_door_servo, target: !lambda "return 4000 * 4;" }}
#     # tilt_lambda: !lambda "return id(right_door_servo).current_position;"
#     # lambda: "return id(right_door_servo).current_position < 200 ? esphome::cover::COVER_CLOSED : esphome::cover::COVER_OPEN;"
#     close_action: { lambda: !lambda "id(garage_door_controller).move_servo(-(400 * 8), false, 400, 200, 20);" }
#     tilt_action: { lambda: !lambda "id(garage_door_controller).move_servo(400 * 8, false, 400, 200, 20);" }
#     tilt_lambda: !lambda "return 0;"
#     lambda: !lambda "return esphome::cover::COVER_CLOSED;"


# 400steps per rotation
# stepper:
#   - platform: a4988
#     id: right_door_servo
#     step_pin: $step_pin
#     dir_pin: $dir_pin
#     sleep_pin: $en_pin
#     # max_speed: 16000 steps/s # 2400 RPM
#     # acceleration: 8000
#     # deceleration: 8000
#     max_speed: 4000 steps/s # 2400 RPM
#     acceleration: 2000
#     deceleration: 2000




