esphome:
  name: $devicename

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: "MuskFi"
  password: "123456789"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "$devicename AP"
    password: "BiSG9yrKP394"

captive_portal:
    

external_components:
  # use all components from a local folder
  - source:
      type: local
      path: ../my_components

i2c:
   - id: bus_a
     sda: $sda_pin
     scl: $scl_pin
     scan: true

sensor:
  - platform: sht4x
    update_interval: 30s
    i2c_id: bus_a
    temperature:
      name: "Temperature"
      id: temp
      unit_of_measurement: "째F"
      filters:
        - lambda: return x * (9.0/5.0) + 32.0;
    humidity:
      name: "Relative Humidity"
      id: humid


  - platform: rotary_encoder
    id: dial
    pin_a: 
      number: $encode_pin_1
      mode: INPUT
    pin_b:
      number: $encode_pin_2
      mode: INPUT # _PULLUP external pull up resistor required

switch:
  #heater
  - platform: gpio
    pin: $relay_pin
    id: heaterLow
    restore_mode: always_off
  - platform: gpio
    pin: $relay_pin2
    id: heaterHigh
    restore_mode: always_off

climate:
  - platform: thermostat
    internal: false
    id: therm
    name: $thermostat_name
    # unit_of_measurement: "째F"
    sensor: temp
    #heating config
    heat_deadband: 0.1 째F
    heat_overrun: 0.1 째F
    min_heating_off_time: 60 s
    min_heating_run_time: 60 s
    heat_action:
      switch.turn_on: heaterLow
    supplemental_heating_action:
      switch.turn_on: heaterHigh
    max_heating_run_time: 90 min
    supplemental_heating_delta: 2
    #idle config
    min_idle_time: 10 min
    idle_action:
      - switch.turn_off: heaterHigh
      - switch.turn_off: heaterLow
    preset:
      # Custom preset
      - name: A custom preset
        default_target_temperature_low: 65
        mode: HEAT