esphome:
  name: $devicename
  includes:
    - ../my_components/Segmented_Epaper.h
    - ../my_components/segment_E_papaer/EPD_1in9.h



esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: "MuskFi"
  password: "123456789"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "$devicename AP"
    password: "BiSG9yrKP394"

captive_portal:

external_components:
  # use all components from a local folder
  - source:
      type: local
      path: ../my_components

i2c:
  - id: bus_a
    sda: $sda_pin
    scl: $scl_pin
    scan: true

custom_component:
  - lambda: |-
      auto ePaper_display = new SegmentedEPaper(id(bus_a));
      return {ePaper_display};
    components:
      - id: segmented_e_paper

time:
  - platform: sntp
    on_time:
      # Every 30s
      - seconds: 0,15,30,45
        then:
          - lambda: |-
              auto ptr = id(segmented_e_paper);
              auto tempVal = id(temp).state;
              static_cast<SegmentedEPaper*>(ptr)->SetAmbientTemp( ((tempVal) * (9.0/5.0)) + 32 );
              auto setpoint = id(therm).target_temperature;
              static_cast<SegmentedEPaper*>(ptr)->SetTempSetpoint( ((setpoint) * (9.0/5.0)) + 32 );

sensor:
  - platform: sht4x
    update_interval: 30s
    i2c_id: bus_a
    temperature:
      name: "Temperature"
      id: temp
      unit_of_measurement: "°C"
    humidity:
      name: "Relative Humidity"
      id: humid

  - platform: rotary_encoder
    id: dial
    pin_a:
      number: $encode_pin_1
      mode: INPUT
    pin_b:
      number: $encode_pin_2
      mode: INPUT # _PULLUP external pull up resistor required
    on_anticlockwise:
      - lambda: auto newTemp = id(therm).target_temperature + (5.0/9.0);
          ESP_LOGD("ccw", "old, %f,  new; %f", id(therm).target_temperature, newTemp);
          auto ptr = id(segmented_e_paper);
          static_cast<SegmentedEPaper*>(ptr)->SetTempSetpoint( ((newTemp) * (9.0/5.0)) + 32 );
          auto call = id(therm).make_call();
          call.set_target_temperature(newTemp);
          call.perform();
    on_clockwise:
      - lambda: auto newTemp = id(therm).target_temperature - (5.0/9.0);
          ESP_LOGD("ccw", "old, %f,  new; %f", id(therm).target_temperature, newTemp);
          auto ptr = id(segmented_e_paper);
          static_cast<SegmentedEPaper*>(ptr)->SetTempSetpoint( ((newTemp) * (9.0/5.0)) + 32 );
          auto call = id(therm).make_call();
          call.set_target_temperature(newTemp);
          call.perform();

switch:
  #heater
  - platform: gpio
    pin: $relay_pin
    id: heaterLow
    restore_mode: always_off
  - platform: gpio
    pin: $relay_pin2
    id: heaterHigh
    restore_mode: always_off

climate:
  - platform: thermostat
    name: $thermostat_name
    sensor: temp
    id: therm
    default_preset: home
    supplemental_heating_delta: 3 °C
    startup_delay: True
    min_heating_off_time: 30s
    min_heating_run_time: 30s
    max_heating_run_time: 180s
    min_idle_time: 30s
    heat_action:
      - switch.turn_on: heaterLow
    supplemental_heating_action:
      - switch.turn_on: heaterHigh
    idle_action:
      - switch.turn_off: heaterLow
      - switch.turn_off: heaterHigh
    preset:
      - name: home
        default_target_temperature_low: 19 °C
        mode: heat
      - name: away
        default_target_temperature_low: 10 °C
        mode: heat
      - name: sleep
        default_target_temperature_low: 18 °C
        mode: heat


